-- =============================================================================
-- mart_inventory.sql
-- Description : Daily inventory state enriched with stockout events,
--               product classifications, and operational KPIs.
--               Primary read surface for the Inventory Risk page.
--               All inventory data is SYNTHETIC (generated by the Monte Carlo
--               simulation engine) — see docs/08_synthetic_data_disclaimer.md.
-- Grain       : one row per (date × store_id × item_id) — daily snapshot
-- Source      : {{ source('gold', 'fact_inventory_snapshot') }}  [SYNTHETIC]
--               {{ source('gold', 'fact_stockout_event') }}      [SYNTHETIC]
--               {{ ref('mart_demand') }}            (demand context)
--               {{ source('gold', 'dim_product') }}
-- Key metrics : stock_on_hand, days_of_supply, fill_rate (rolling 28d),
--               stockout_probability (rolling), overstock_flag,
--               estimated_lost_revenue (from stockout events)
-- Label       : SYNTHETIC — inventory layer generated by simulation engine
-- =============================================================================

WITH

-- ── 1. Inventory snapshot (SYNTHETIC) ───────────────────────────────────────
inv AS (
    SELECT
        date,
        store_id,
        item_id,
        stock_on_hand,
        incoming_orders,
        safety_stock,
        reorder_point,
        days_of_supply,
        is_stockout,
        is_overstock,
        policy_id,
        'SYNTHETIC'                                     AS data_source_tag
    FROM {{ source('gold', 'fact_inventory_snapshot') }}
),

-- ── 2. Stockout events (SYNTHETIC) ──────────────────────────────────────────
-- Grain: one row per stockout event (multi-day runs).
-- We join back to the daily snapshot to distribute event-level metrics
-- across the individual stockout days.
stockout_events AS (
    SELECT
        store_id,
        item_id,
        start_date,
        end_date,
        duration_days,
        estimated_lost_units,
        estimated_lost_revenue,
        root_cause
    FROM {{ source('gold', 'fact_stockout_event') }}
),

-- ── 3. Expand stockout events to daily rows ──────────────────────────────────
-- For each stockout day, attach the event metadata so analysts can filter
-- by root cause or duration bucket directly in the daily mart.
stockout_daily AS (
    SELECT
        i.date,
        i.store_id,
        i.item_id,
        e.duration_days                                 AS stockout_event_duration,
        e.estimated_lost_units                          AS stockout_event_lost_units,
        e.estimated_lost_revenue                        AS stockout_event_lost_revenue,
        e.root_cause                                    AS stockout_root_cause
    FROM inv i
    INNER JOIN stockout_events e
        ON  i.store_id = e.store_id
        AND i.item_id  = e.item_id
        AND i.date     BETWEEN e.start_date AND e.end_date
),

-- ── 4. Demand context from mart_demand ──────────────────────────────────────
demand AS (
    SELECT
        date,
        store_id,
        item_id,
        state_id,
        cat_id,
        dept_id,
        abc_class,
        xyz_class,
        demand_class,
        store_tier,
        units_sold          AS actual_demand,
        rolling_7d_avg      AS demand_7d_avg,
        rolling_28d_avg     AS demand_28d_avg
    FROM {{ ref('mart_demand') }}
),

-- ── 5. Base join ─────────────────────────────────────────────────────────────
joined AS (
    SELECT
        i.date,
        i.store_id,
        i.item_id,
        i.stock_on_hand,
        i.incoming_orders,
        i.safety_stock,
        i.reorder_point,
        i.days_of_supply,
        i.is_stockout,
        i.is_overstock,
        i.policy_id,
        i.data_source_tag,

        -- Demand context
        d.state_id,
        d.cat_id,
        d.dept_id,
        d.abc_class,
        d.xyz_class,
        d.demand_class,
        d.store_tier,
        d.actual_demand,
        d.demand_7d_avg,
        d.demand_28d_avg,

        -- Stockout event details (NULL when no active stockout)
        s.stockout_event_duration,
        s.stockout_event_lost_units,
        s.stockout_event_lost_revenue,
        s.stockout_root_cause

    FROM inv i
    LEFT JOIN demand         d ON i.date = d.date AND i.store_id = d.store_id AND i.item_id = d.item_id
    LEFT JOIN stockout_daily s ON i.date = s.date AND i.store_id = s.store_id AND i.item_id = s.item_id
),

-- ── 6. Rolling fill rate (28d) ───────────────────────────────────────────────
-- Fill rate = % of days NOT in stockout in the last 28 days.
-- A proxy for service level experienced by customers.
rolling_kpis AS (
    SELECT
        *,

        -- Fill rate: rolling 28-day window
        1.0 - AVG(CAST(is_stockout AS FLOAT))
            OVER (
                PARTITION BY store_id, item_id
                ORDER BY date
                ROWS BETWEEN 27 PRECEDING AND CURRENT ROW
            )                                           AS fill_rate_28d,

        -- Stockout probability: rolling 91-day (captures seasonal patterns)
        AVG(CAST(is_stockout AS FLOAT))
            OVER (
                PARTITION BY store_id, item_id
                ORDER BY date
                ROWS BETWEEN 90 PRECEDING AND CURRENT ROW
            )                                           AS stockout_prob_91d,

        -- Overstock rate: rolling 28-day
        AVG(CAST(is_overstock AS FLOAT))
            OVER (
                PARTITION BY store_id, item_id
                ORDER BY date
                ROWS BETWEEN 27 PRECEDING AND CURRENT ROW
            )                                           AS overstock_rate_28d,

        -- Average inventory held (for carrying cost calculation)
        AVG(stock_on_hand)
            OVER (
                PARTITION BY store_id, item_id
                ORDER BY date
                ROWS BETWEEN 27 PRECEDING AND CURRENT ROW
            )                                           AS avg_inventory_28d,

        -- Inventory turnover proxy: demand / avg_inventory (annualised)
        CASE
            WHEN AVG(stock_on_hand) OVER (
                     PARTITION BY store_id, item_id
                     ORDER BY date
                     ROWS BETWEEN 27 PRECEDING AND CURRENT ROW
                 ) > 0
            THEN demand_28d_avg * 365.0
                 / NULLIF(
                     AVG(stock_on_hand) OVER (
                         PARTITION BY store_id, item_id
                         ORDER BY date
                         ROWS BETWEEN 27 PRECEDING AND CURRENT ROW
                     ), 0
                   )
            ELSE NULL
        END                                             AS inventory_turnover_annualised

    FROM joined
),

-- ── 7. Risk tier classification ──────────────────────────────────────────────
-- Operationally useful: classify each SKU-day into a risk bucket.
-- Thresholds chosen to match the alert engine rules in spec §11.
with_risk AS (
    SELECT
        *,
        CASE
            WHEN is_stockout                     THEN 'STOCKOUT'
            WHEN stockout_prob_91d >= 0.50       THEN 'HIGH_RISK'
            WHEN stockout_prob_91d >= 0.25       THEN 'MEDIUM_RISK'
            WHEN is_overstock                    THEN 'OVERSTOCK'
            ELSE                                      'HEALTHY'
        END                                         AS risk_tier,

        -- Days of supply bucket (for histogram in dashboard)
        CASE
            WHEN days_of_supply IS NULL          THEN 'UNKNOWN'
            WHEN days_of_supply = 0              THEN '0'
            WHEN days_of_supply < 7              THEN '1-7'
            WHEN days_of_supply < 14             THEN '7-14'
            WHEN days_of_supply < 30             THEN '14-30'
            WHEN days_of_supply < 60             THEN '30-60'
            ELSE                                      '60+'
        END                                         AS dos_bucket

    FROM rolling_kpis
),

-- ── 8. Final ─────────────────────────────────────────────────────────────────
final AS (
    SELECT
        -- Natural keys
        date,
        store_id,
        item_id,

        -- Hierarchy
        state_id,
        cat_id,
        dept_id,
        abc_class,
        xyz_class,
        demand_class,
        store_tier,

        -- Inventory state
        stock_on_hand,
        incoming_orders,
        safety_stock,
        reorder_point,
        days_of_supply,
        dos_bucket,
        is_stockout,
        is_overstock,
        risk_tier,
        policy_id,
        data_source_tag,

        -- Demand context
        actual_demand,
        demand_7d_avg,
        demand_28d_avg,

        -- Rolling KPIs
        fill_rate_28d,
        stockout_prob_91d,
        overstock_rate_28d,
        avg_inventory_28d,
        inventory_turnover_annualised,

        -- Stockout event details
        stockout_event_duration,
        stockout_event_lost_units,
        stockout_event_lost_revenue,
        stockout_root_cause,

        CURRENT_TIMESTAMP AS _dbt_loaded_at
    FROM with_risk
)

SELECT * FROM final
